### ISSUE TITLE
Prediction Markets

### ISSUE THREAD

**Issue by burrrata** [DAOresear-ch/ideas#11]
Half of the fun of this analysis thing is actually identifying and recommending the levers that need to be pulled to affect positive change. Often this is hard because:
- people don't read the data
- people don't have the background knowledge to process the data
- people don't want the data to be right
- the data might not be right

Beyond just a hand wavey recommendation, opening a prediction market on the price of token X if suggestion Y is implemented would be a much more concrete way to instill confidence and affect change. (assuming there's a prediction market out there that actually has liquidity/users)

**Comment by pythonpete32** [comment]
a few months back I tested out the LevelK dapp with the team, it's still very primitive and won't be available for a while but Gnosis, on the other hand, has made big strides. I need to do a deep-dive into what is possible but I do know they are now using bonding curve to sidestep some of the issues with liquidity depth and importantly they have conditional markets.
