### ISSUE TITLE
Analytics and Stats

### ISSUE THREAD

**Issue by burrrata** [DAOresear-ch/ideas#3]
Like [Messari](https://www.messari.io/), but for DAOs. This could include metrics ike
- voting activity
- funds held in treasury
- DAO token supply schedule
- token price
- etc... 

Would be a great extensions/collaboration with [Apiary](https://github.com/1Hive/apiary) and/or [Scout](https://scout.cool/)

**Comment by pythonpete32** [comment]
This is an excellent idea. Maybe we could use the Apiary API and extend it with the same script I used to make the [AGP Dashboard](https://datastudio.google.com/open/1VsK1vef-AjKeAzmR7TWJBsu65rFbRrtI) this would be a very useful research tool
