### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by burrrata** [DAOresear-ch/ideas#6]
Wiki
- information on all the different DAO models out there (so if you wanted to use a DAO for something there would be a directory of DAOs with a high level discription and then links to the project page and code - think [Messari](https://messari.io/) for DAOs

The community could signal/vote on important things to explore/cover via an [Aragon](https://aragon.org/) DAO

The Wiki could be hosted on GitHub initially, but eventually live within the DAO itself
- https://github.com/p2pmodels/wiki

A protocol like [SourceCred](https://sourcecred.io/) could be used to reward contributors to the GitHub repos and Discourse forum

**Comment by burrrata** [comment]
Community Rewards for Wiki contributors
- automatic SourceCred distributions
- weekly community allocation dot votes
- bounties posted by people/orgs requesting research by the community

**Comment by pythonpete32** [comment]
This seems like it should be the core thing we should e working on as it binds everything else together. it's also where we can test out and validate other projects we are working on like CRDAO
