### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by burrrata** [DAOresear-ch/ideas#8]
If we're going to cover a lot of different DAOs, does it make sense to roll our own forum that's not just Aragon related?

Note: this is not an issue atm as we're starting with ANT and Aragon DAOs, but in the future it might be worth considering. Having a place for people to just jam about DAOs in general could be a win for all parties involved, Aragon and beyond.

**Comment by pythonpete32** [comment]
TBH I think this is something we will probably want to do pretty early on, once we have a firm idea of what DAOresearch is, its scope and start working on putting the material together, we should launch it. the only thing we need to be cognisant about is not doing too much while too early. we need will need tight focus while is just the two of us

**Comment by burrrata** [comment]
Apparently [DAO Talk](https://daotalk.org/) is a thing
